### ISSUE TITLE
ChakraUI wrapper tracking

### ISSUE THREAD

**Issue by ricardocosta** [ricardocosta/bank-ui#176]
## Description

In order to avoid leaking the usage of ChakraUI, we will expose it under a new scope. This opens the possibility of changing the UI library in the future without affecting the dependent apps.

This issue tracks the progress on adding wrappers to the different ChakraUI packages
- [x] `@chakra-ui/accordion` #199
- [x] `@chakra-ui/alert` #210
- [x] `@chakra-ui/avatar` #202 
- [x] `@chakra-ui/breadcrumb` #201
- [x] `@chakra-ui/button` #131 
- [x] `@chakra-ui/card` #182 
- [x] `@chakra-ui/checkbox` #186 
- [x] `@chakra-ui/close-button` #206
- [x] ~`@chakra-ui/control-box`~
- [x] `@chakra-ui/counter` #215
- [x] ~`@chakra-ui/css-reset`~
- [x] `@chakra-ui/editable` #187 
- [x] `@chakra-ui/form-control` #188 
- [x] `@chakra-ui/hooks` #214
- [x] `@chakra-ui/icon` #204 
- [x] `@chakra-ui/image` #205
- [x] `@chakra-ui/input` #189
- [x] `@chakra-ui/layout` #177
- [x] `@chakra-ui/media-query` #208
- [x] `@chakra-ui/menu` #197
- [x] `@chakra-ui/modal` #179
- [x] `@chakra-ui/number-input` #358
- [x] `@chakra-ui/pin-input` #359 
- [x] `@chakra-ui/popover` #196
- [x] ~`@chakra-ui/popper`~
- [x] `@chakra-ui/portal` #207
- [x] `@chakra-ui/progress` #211
- [x] `@chakra-ui/radio` #190 
- [x] ~`@chakra-ui/react-env`~
- [x] `@chakra-ui/select` #193
- [x] `@chakra-ui/skeleton` #178
- [x] `@chakra-ui/skip-nav` #203
- [x] `@chakra-ui/slider` #192
- [x] `@chakra-ui/spinner` #180
- [x] `@chakra-ui/stat` #184
- [x] `@chakra-ui/switch` #194
- [x] ~`@chakra-ui/system`~
- [x] `@chakra-ui/table` #183
- [x] `@chakra-ui/tabs` #198
- [x] `@chakra-ui/tag` #185
- [x] `@chakra-ui/textarea` #213
- [x] `@chakra-ui/theme` #150
- [x] `@chakra-ui/toast` #212
- [x] `@chakra-ui/tooltip` #181
- [x] `@chakra-ui/transition` #209
- [x] `@chakra-ui/visually-hidden` #200
- [x] `@chakra-ui/theme-utils` #150 
- [x] `./chakra-provider` #130
